version: 2.1
orbs:
  python: circleci/python@0.3.0
workflows:
  main:
    jobs:
      - test
      - build

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Run tests
          command: python -m unittest
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Build project scripts
          command: |
            sh build.sh
      - store_artifacts:
          path: ./dist
